# Generated by Django 3.2.9 on 2021-12-04 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('image_url', models.ImageField(upload_to='post_img')),
                ('region', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('categories', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
